import type {
  BucketDraft,
  InvestmentBucket,
  InvestorTransaction,
  PortfolioHolding,
} from "./types"

export const ATLAS_INVESTOR_ID = "inv-atlas"
export const FRESH_INVESTOR_ID = "inv-fresh"

export const BUCKET_HIGH_QUALITY_ID = "bucket-high-quality"
export const BUCKET_AGRICULTURE_ID = "bucket-agriculture"
export const BUCKET_SHORT_DURATION_ID = "bucket-short-duration"

export function defaultBucketDraft(): BucketDraft {
  return {
    name: "",
    capitalCap: 1_000_000,
    requiredApr: 11,
    scoreMin: 0,
    scoreMax: 100,
    industries: ["Any"],
    tenorMin: 0,
    tenorMax: 60,
  }
}

export function bucketToDraft(bucket: InvestmentBucket): BucketDraft {
  return {
    name: bucket.name,
    capitalCap: bucket.capitalCap,
    requiredApr: bucket.requiredApr,
    scoreMin: bucket.scoreMin,
    scoreMax: bucket.scoreMax,
    industries: [...bucket.industries],
    tenorMin: bucket.tenorMin ?? 0,
    tenorMax: bucket.tenorMax ?? 60,
    invoiceMin: bucket.invoiceMin,
    invoiceMax: bucket.invoiceMax,
    minimumConfidence: bucket.minimumConfidence,
    minHistoricalInvoices: bucket.minHistoricalInvoices,
    minPlatformRepayments: bucket.minPlatformRepayments,
    maxLatePaymentRate: bucket.maxLatePaymentRate,
    maxBuyerExposure: bucket.maxBuyerExposure,
    maxSellerExposure: bucket.maxSellerExposure,
    maxBuyerPortfolioPercent: bucket.maxBuyerPortfolioPercent,
  }
}

export const ATLAS_BUCKETS: InvestmentBucket[] = [
  {
    id: BUCKET_HIGH_QUALITY_ID,
    name: "High Quality — Any Industry",
    investorId: ATLAS_INVESTOR_ID,
    capitalCap: 2_000_000,
    requiredApr: 10,
    scoreMin: 80,
    scoreMax: 100,
    industries: ["Any"],
    tenorMin: 0,
    tenorMax: 45,
    currentExposure: 780_000,
    status: "active",
  },
  {
    id: BUCKET_AGRICULTURE_ID,
    name: "Agriculture",
    investorId: ATLAS_INVESTOR_ID,
    capitalCap: 3_000_000,
    requiredApr: 11,
    scoreMin: 50,
    scoreMax: 100,
    industries: ["Agriculture"],
    tenorMin: 0,
    tenorMax: 60,
    currentExposure: 1_250_000,
    status: "active",
  },
  {
    id: BUCKET_SHORT_DURATION_ID,
    name: "Very High Quality / Short Term",
    investorId: ATLAS_INVESTOR_ID,
    capitalCap: 1_000_000,
    requiredApr: 8.5,
    scoreMin: 90,
    scoreMax: 100,
    industries: ["Any"],
    tenorMin: 0,
    tenorMax: 20,
    currentExposure: 620_000,
    status: "active",
  },
]

export const ATLAS_HOLDINGS: PortfolioHolding[] = [
  {
    id: "hold-1",
    buyerName: "Rede Brasil Foods",
    sellerName: "ABC Industrial Ltda.",
    amountInvested: 220_000,
    faceValue: 224_000,
    apr: 11.5,
    score: 91,
    daysToMaturity: 21,
    bucketId: BUCKET_HIGH_QUALITY_ID,
    bucketName: "High Quality",
    status: "Current",
  },
  {
    id: "hold-2",
    buyerName: "Mercado Sul",
    sellerName: "ABC Industrial Ltda.",
    amountInvested: 180_000,
    faceValue: 185_000,
    apr: 11.2,
    score: 86,
    daysToMaturity: 28,
    bucketId: BUCKET_HIGH_QUALITY_ID,
    bucketName: "High Quality",
    status: "Current",
  },
  {
    id: "hold-3",
    buyerName: "Atlas Atacado",
    sellerName: "Nova Comércio Ltda.",
    amountInvested: 210_000,
    faceValue: 216_000,
    apr: 11.6,
    score: 88,
    daysToMaturity: 18,
    bucketId: BUCKET_HIGH_QUALITY_ID,
    bucketName: "High Quality",
    status: "Current",
  },
  {
    id: "hold-4",
    buyerName: "Litoral Pack",
    sellerName: "ABC Industrial Ltda.",
    amountInvested: 170_000,
    faceValue: 174_000,
    apr: 11.7,
    score: 84,
    daysToMaturity: 34,
    bucketId: BUCKET_HIGH_QUALITY_ID,
    bucketName: "High Quality",
    status: "Current",
  },
  {
    id: "hold-5",
    buyerName: "Agro Norte",
    sellerName: "ABC Industrial Ltda.",
    amountInvested: 310_000,
    faceValue: 318_000,
    apr: 12.4,
    score: 78,
    daysToMaturity: 34,
    bucketId: BUCKET_AGRICULTURE_ID,
    bucketName: "Agriculture",
    status: "Current",
  },
  {
    id: "hold-6",
    buyerName: "Agro Distribuição",
    sellerName: "Campo Forte Ltda.",
    amountInvested: 280_000,
    faceValue: 288_000,
    apr: 12.8,
    score: 82,
    daysToMaturity: 26,
    bucketId: BUCKET_AGRICULTURE_ID,
    bucketName: "Agriculture",
    status: "Current",
  },
  {
    id: "hold-7",
    buyerName: "Rede Brasil Foods",
    sellerName: "ABC Industrial Ltda.",
    amountInvested: 320_000,
    faceValue: 328_000,
    apr: 12.2,
    score: 86,
    daysToMaturity: 21,
    bucketId: BUCKET_AGRICULTURE_ID,
    bucketName: "Agriculture",
    status: "Current",
  },
  {
    id: "hold-8",
    buyerName: "Mercado Sul",
    sellerName: "ABC Industrial Ltda.",
    amountInvested: 200_000,
    faceValue: 206_000,
    apr: 13.1,
    score: 74,
    daysToMaturity: 30,
    bucketId: BUCKET_AGRICULTURE_ID,
    bucketName: "Agriculture",
    status: "Current",
  },
  {
    id: "hold-9",
    buyerName: "Fazenda Sul",
    sellerName: "Vale Verde Ltda.",
    amountInvested: 140_000,
    faceValue: 144_000,
    apr: 12.5,
    score: 70,
    daysToMaturity: 42,
    bucketId: BUCKET_AGRICULTURE_ID,
    bucketName: "Agriculture",
    status: "Current",
  },
  {
    id: "hold-10",
    buyerName: "Costa Imports",
    sellerName: "Costa Exportadora Ltda.",
    amountInvested: 180_000,
    faceValue: 184_000,
    apr: 8.9,
    score: 94,
    daysToMaturity: 12,
    bucketId: BUCKET_SHORT_DURATION_ID,
    bucketName: "Short Duration",
    status: "Current",
  },
  {
    id: "hold-11",
    buyerName: "Atlas Atacado",
    sellerName: "Nova Comércio Ltda.",
    amountInvested: 140_000,
    faceValue: 143_000,
    apr: 9.1,
    score: 92,
    daysToMaturity: 16,
    bucketId: BUCKET_SHORT_DURATION_ID,
    bucketName: "Short Duration",
    status: "Current",
  },
  {
    id: "hold-12",
    buyerName: "Litoral Pack",
    sellerName: "ABC Industrial Ltda.",
    amountInvested: 110_000,
    faceValue: 113_000,
    apr: 8.7,
    score: 93,
    daysToMaturity: 8,
    bucketId: BUCKET_SHORT_DURATION_ID,
    bucketName: "Short Duration",
    status: "Current",
  },
  {
    id: "hold-13",
    buyerName: "Costa Imports",
    sellerName: "Leste Distribuidora Ltda.",
    amountInvested: 100_000,
    faceValue: 102_000,
    apr: 8.8,
    score: 91,
    daysToMaturity: 14,
    bucketId: BUCKET_SHORT_DURATION_ID,
    bucketName: "Short Duration",
    status: "Current",
  },
  {
    id: "hold-14",
    buyerName: "Atlas Atacado",
    sellerName: "Nova Comércio Ltda.",
    amountInvested: 90_000,
    faceValue: 92_000,
    apr: 9.0,
    score: 90,
    daysToMaturity: 18,
    bucketId: BUCKET_SHORT_DURATION_ID,
    bucketName: "Short Duration",
    status: "Current",
  },
]

export const ATLAS_TRANSACTIONS: InvestorTransaction[] = [
  {
    id: "tx-1",
    at: "Today 14:32",
    kind: "invoice_purchased",
    amount: -220_000,
    counterparty: "Rede Brasil Foods",
    note: "High Quality bucket",
  },
  {
    id: "tx-2",
    at: "Today 11:04",
    kind: "invoice_repaid",
    amount: 184_200,
    counterparty: "Mercado Sul",
  },
  {
    id: "tx-5",
    at: "Yesterday 13:05",
    kind: "invoice_purchased",
    amount: -310_000,
    counterparty: "Agro Norte",
    note: "Agriculture bucket",
  },
  {
    id: "tx-6",
    at: "Yesterday 10:22",
    kind: "investor_repayment",
    amount: 142_800,
    counterparty: "Atlas Atacado",
  },
  {
    id: "tx-7",
    at: "3 days ago",
    kind: "bucket_changed",
    amount: 0,
    note: "Agriculture max tenor set to 60 days",
  },
  {
    id: "tx-8",
    at: "5 days ago",
    kind: "capital_deposited",
    amount: 5_000_000,
    note: "Initial RLUSD deposit",
  },
]
